apiVersion: cam.tencentcloud.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: cam/v1alpha1/group
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: tf_cam_group
    remark: tf_group_remark
