apiVersion: sqlserver.tencentcloud.crossplane.io/v1alpha1
kind: PublishSubscribe
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/publishsubscribe
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    databaseTuples:
    - publishDatabase: tf_example_db
      subscribeDatabase: tf_example_db
    deleteSubscribeDb: false
    publishInstanceId: ${tencentcloud_sqlserver_general_cloud_instance.example_pub.id}
    publishSubscribeName: example
    subscribeInstanceId: ${tencentcloud_sqlserver_general_cloud_instance.example_sub.id}

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/publishsubscribe
  labels:
    testing.upbound.io/example-name: security_group
  name: security-group
spec:
  forProvider:
    description: desc.
    name: sg-example

---

apiVersion: sqlserver.tencentcloud.crossplane.io/v1alpha1
kind: DB
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/publishsubscribe
  labels:
    testing.upbound.io/example-name: example_pub
  name: example-pub
spec:
  forProvider:
    charset: Chinese_PRC_BIN
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_pub
    name: tf_example_db_pub
    remark: test-remark

---

apiVersion: sqlserver.tencentcloud.crossplane.io/v1alpha1
kind: DB
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/publishsubscribe
  labels:
    testing.upbound.io/example-name: example_sub
  name: example-sub
spec:
  forProvider:
    charset: Chinese_PRC_BIN
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_sub
    name: tf_example_db_sub
    remark: test-remark

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/publishsubscribe
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones_by_product.zones.zones.4.name}
    cidrBlock: 10.0.0.0/16
    isMulticast: false
    name: subnet-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/publishsubscribe
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc-example
