apiVersion: vpc.tencentcloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-subnet
spec:
  forProvider:
    availabilityZone: "ap-guangzhou-1"
    cidrBlock: "10.1.2.0/24"
    name: "test-crossplane-subnet"
    vpcidRef:
      name: "example-vpc"