apiVersion: dcdb.tencentcloud.crossplane.io/v1alpha1
kind: DcdbAccount
metadata:
  annotations:
    meta.upbound.io/example-id: dcdb/v1alpha1/dcdbaccount
  labels:
    testing.upbound.io/example-name: account
  name: account
spec:
  forProvider:
    description: this is a test account
    host: 127.0.0.1
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    maxUserConnections: 10
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    readOnly: 0
    userName: mysql
