apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Eip
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eip
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    bandwidthPackageId: bwp-jtvzuky6
    internetChargeType: BANDWIDTH_PACKAGE
    name: awesome_gateway_ip
    type: EIP
