apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: EipAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    eipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eip
    instanceId: ${tencentcloud_instance.example.id}

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Eip
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipassociation
  labels:
    testing.upbound.io/example-name: eip
  name: eip
spec:
  forProvider:
    internetChargeType: TRAFFIC_POSTPAID_BY_HOUR
    name: example-eip
    type: EIP

---

apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.zones.zones.0.name}
    disableMonitorService: true
    disableSecurityService: true
    imageId: ${data.tencentcloud_images.image.images.0.image_id}
    instanceName: example-cvm
    instanceType: ${data.tencentcloud_instance_types.instance_types.instance_types.0.instance_type}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    systemDiskType: CLOUD_PREMIUM
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipassociation
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.zones.zones.0.name}
    cidrBlock: 10.0.0.0/16
    isMulticast: false
    name: example-vpc
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipassociation
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: example-vpc
