apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPCAcl
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpcacl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    egress:
    - ACCEPT#192.168.1.0/24#800#TCP
    - ACCEPT#192.168.1.0/24#800-900#TCP
    ingress:
    - ACCEPT#192.168.1.0/24#800#TCP
    - ACCEPT#192.168.1.0/24#800-900#TCP
    name: tf-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpcacl
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc-example
