apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPVAclAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpvaclattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
spec:
  forProvider:
    aclIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpvaclattachment
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.zones.zones.0.name}
    cidrBlock: 10.0.0.0/16
    name: subnet-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpvaclattachment
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc-example

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPCAcl
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpvaclattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    egress:
    - ACCEPT#192.168.1.0/24#800#TCP
    - ACCEPT#192.168.1.0/24#800-900#TCP
    ingress:
    - ACCEPT#192.168.1.0/24#800#TCP
    - ACCEPT#192.168.1.0/24#800-900#TCP
    name: tf-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc
