apiVersion: apigateway.tencentcloud.crossplane.io/v1alpha1
kind: ApiKey
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1alpha1/apikey
  labels:
    testing.upbound.io/example-name: example_auto
  name: example-auto
spec:
  forProvider:
    secretName: tf_example_auto
    status: "on"
