apiVersion: apigateway.tencentcloud.crossplane.io/v1alpha1
kind: UsagePlanAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1alpha1/usageplanattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    bindType: API
    environment: release
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    usagePlanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: apigateway.tencentcloud.crossplane.io/v1alpha1
kind: Api
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1alpha1/usageplanattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiDesc: my hello api update
    apiName: tf_example
    authType: SECRET
    enableCors: true
    protocol: HTTP
    requestConfigMethod: POST
    requestConfigPath: /user/info
    requestParameters:
    - defaultValue: test@qq.com
      desc: desc.
      name: email
      position: QUERY
      required: true
      type: string
    responseErrorCodes:
    - code: 500
      convertedCode: 5000
      desc: system error code
      msg: system error
      needConvert: true
    responseFailExample: <note>fail</note>
    responseSuccessExample: <note>success</note>
    responseType: XML
    serviceConfigMethod: POST
    serviceConfigPath: /user
    serviceConfigTimeout: 10
    serviceConfigType: HTTP
    serviceConfigUrl: http://www.tencent.com
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: apigateway.tencentcloud.crossplane.io/v1alpha1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1alpha1/usageplanattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ipVersion: IPv4
    netType:
    - INNER
    - OUTER
    protocol: http&https
    serviceDesc: desc.
    serviceName: tf_example

---

apiVersion: apigateway.tencentcloud.crossplane.io/v1alpha1
kind: UsagePlan
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1alpha1/usageplanattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    maxRequestNum: 100
    maxRequestNumPreSec: 10
    usagePlanDesc: desc.
    usagePlanName: tf_example
