apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: ListenerRule
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/listenerrule
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    certificateCaId: VfqO4zkB
    certificateId: VjANRdz8
    certificateSslMode: MUTUAL
    clbIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    domain: foo.net
    healthCheckHealthNum: 3
    healthCheckHttpCode: 2
    healthCheckHttpDomain: Default Domain
    healthCheckHttpMethod: GET
    healthCheckHttpPath: Default Path
    healthCheckIntervalTime: 5
    healthCheckSwitch: true
    healthCheckUnhealthNum: 3
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    scheduler: WRR
    sessionExpireTime: 30
    url: /bar
