apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: Listener
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: HTTP_listener
  name: http-listener
spec:
  forProvider:
    clbIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    listenerName: test_listener
    port: 80
    protocol: HTTP
