apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: LogTopic
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/logtopic
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider:
    logSetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: set
    topicName: clb-topic
