apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clbName: tf-example
    networkType: INTERNAL
    projectId: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    tags:
      tagKey: tagValue
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ap-guangzhou-4
    cidrBlock: 10.0.1.0/24
    name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
