apiVersion: mongodb.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: mongodb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: mongodb
  name: mongodb
spec:
  forProvider:
    availableZone: ap-guangzhou-2
    engineVersion: MONGO_36_WT
    instanceName: mongodb
    machineType: HIO10G
    memory: 4
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    projectId: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    volume: 100
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
