apiVersion: cbs.tencentcloud.crossplane.io/v1alpha1
kind: StorageAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: cbs/v1alpha1/storageattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
