apiVersion: audit.tencentcloud.crossplane.io/v1alpha1
kind: Audit
metadata:
  annotations:
    meta.upbound.io/example-id: audit/v1alpha1/audit
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    auditSwitch: true
    cosBucket: test
    cosRegion: ap-hongkong
    logFilePrefix: test
    name: audittest
    readWriteAttribute: 3
