apiVersion: tcm.tencentcloud.crossplane.io/v1alpha1
kind: Mesh
metadata:
  annotations:
    meta.upbound.io/example-id: tcm/v1alpha1/mesh
  labels:
    testing.upbound.io/example-name: mesh
  name: mesh
spec:
  forProvider:
    config:
    - inject:
      - excludeIpRanges:
        - 172.16.0.0/16
        holdApplicationUntilProxyStarts: true
        holdProxyUntilApplicationEnds: true
      istio:
      - disableHttpRetry: true
        disablePolicyChecks: true
        enablePilotHttp: true
        outboundTrafficPolicy: ALLOW_ANY
        smartDns:
        - istioMetaDnsAutoAllocate: true
          istioMetaDnsCapture: true
        tracing:
        - enable: false
      prometheus:
      - customProm:
        - authType: none
          url: https://10.0.0.1:1000
          vpcId: vpc-j9yhbzpn
      sidecarResources:
      - limits:
        - name: cpu
          quantity: "2"
        - name: memory
          quantity: 1Gi
        requests:
        - name: cpu
          quantity: 100m
        - name: memory
          quantity: 128Mi
      tracing:
      - apm:
        - enable: true
          region: ap-guangzhou
        enable: true
        sampling: 1
    displayName: test_mesh
    meshVersion: 1.12.5
    tagList:
    - key: key
      passthrough: false
      value: value
    type: HOSTED
