apiVersion: tdmq.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: tdmq/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    clusterName: example
    remark: this is description.
    tags:
      createdBy: terraform
