apiVersion: ccn.tencentcloud.crossplane.io/v1alpha1
kind: CCN
metadata:
  annotations:
    meta.upbound.io/example-id: ccn/v1alpha1/ccn
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bandwidthLimitType: INTER_REGION_LIMIT
    chargeType: PREPAID
    description: desc.
    name: tf-example
    qos: AG
    tags:
      createBy: terraform
