apiVersion: vod.tencentcloud.crossplane.io/v1alpha1
kind: SubApplication
metadata:
  annotations:
    meta.upbound.io/example-id: vod/v1alpha1/subapplication
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    description: this is sub application
    name: foo
    status: "On"
