apiVersion: vod.tencentcloud.crossplane.io/v1alpha1
kind: SuperPlayerConfig
metadata:
  annotations:
    meta.upbound.io/example-id: vod/v1alpha1/superplayerconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    comment: test
    domain: Default
    drmStreamingInfo:
    - simpleAesDefinition: ${tencentcloud_vod_adaptive_dynamic_streaming_template.foo.id}
    drmSwitch: true
    imageSpriteDefinition: ${tencentcloud_vod_image_sprite_template.foo.id}
    name: tf-super-player
    resolutionNames:
    - minEdgeLength: 889
      name: test1
    - minEdgeLength: 890
      name: test2
    scheme: Default

---

apiVersion: vod.tencentcloud.crossplane.io/v1alpha1
kind: AdaptiveDynamicStreamingTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: vod/v1alpha1/superplayerconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    comment: test
    disableHigherVideoBitrate: false
    disableHigherVideoResolution: false
    drmType: SimpleAES
    format: HLS
    name: tf-adaptive
    streamInfo:
    - audio:
      - audioChannel: dual
        bitrate: 129
        codec: libmp3lame
        sampleRate: 44100
      removeAudio: false
      video:
      - bitrate: 129
        codec: libx265
        fillType: stretch
        fps: 4
        height: 128
        resolutionAdaptive: false
        width: 128
    - audio:
      - bitrate: 256
        codec: libfdk_aac
        sampleRate: 44100
      removeAudio: true
      video:
      - bitrate: 256
        codec: libx264
        fps: 4

---

apiVersion: vod.tencentcloud.crossplane.io/v1alpha1
kind: ImageSpriteTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: vod/v1alpha1/superplayerconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    columnCount: 3
    comment: test
    fillType: stretch
    height: 128
    name: tf-sprite
    resolutionAdaptive: false
    rowCount: 3
    sampleInterval: 10
    sampleType: Percent
    width: 128
