apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: cvm/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: cvm_postpaid
  name: cvm-postpaid
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.my_favorite_zones.zones.0.name}
    dataDisks:
    - dataDiskSize: 50
      dataDiskType: CLOUD_PREMIUM
      encrypt: false
    hostname: user
    imageId: ${data.tencentcloud_images.my_favorite_image.images.0.image_id}
    instanceName: cvm_postpaid
    instanceType: ${data.tencentcloud_instance_types.my_favorite_instance_types.instance_types.0.instance_type}
    projectId: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app
    systemDiskSize: 50
    systemDiskType: CLOUD_PREMIUM
    tags:
      tagKey: tagValue
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: cvm/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.my_favorite_zones.zones.0.name}
    cidrBlock: 10.0.1.0/24
    name: awesome_app_subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: cvm/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: awesome_app_vpc
