apiVersion: cdh.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: cdh/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    chargeType: PREPAID
    hostName: test
    hostType: HC20
    prepaidPeriod: 1
    prepaidRenewFlag: NOTIFY_AND_MANUAL_RENEW
