apiVersion: ses.tencentcloud.crossplane.io/v1alpha1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: ses/v1alpha1/domain
  labels:
    testing.upbound.io/example-name: domain
  name: domain
spec:
  forProvider:
    emailIdentity: iac.cloud
