apiVersion: ses.tencentcloud.crossplane.io/v1alpha1
kind: EmailAddress
metadata:
  annotations:
    meta.upbound.io/example-id: ses/v1alpha1/emailaddress
  labels:
    testing.upbound.io/example-name: email_address
  name: email-address
spec:
  forProvider:
    emailAddress: aaa@iac-tf.cloud
    emailSenderName: aaa
