apiVersion: tke.tencentcloud.crossplane.io/v1alpha1
kind: AddonAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: tke/v1alpha1/addonattachment
  labels:
    testing.upbound.io/example-name: addon_cbs
  name: addon-cbs
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: cbs
    values:
    - rootdir=/var/lib/kubelet
