apiVersion: tke.tencentcloud.crossplane.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: tke/v1alpha1/nodepool
  labels:
    testing.upbound.io/example-name: mynodepool
  name: mynodepool
spec:
  forProvider:
    autoScalingConfig:
    - dataDisk:
      - diskSize: 50
        diskType: CLOUD_PREMIUM
      enhancedMonitorService: false
      enhancedSecurityService: false
      hostName: 12.123.0.0
      hostNameStyle: ORIGINAL
      instanceType: ${var.default_instance_type}
      internetChargeType: TRAFFIC_POSTPAID_BY_HOUR
      internetMaxBandwidthOut: 10
      orderlySecurityGroupIds:
      - sg-24vswocp
      passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      publicIpAssigned: true
      systemDiskSize: "50"
      systemDiskType: CLOUD_PREMIUM
    clusterId: ${tencentcloud_kubernetes_cluster.managed_cluster.id}
    desiredCapacity: 4
    enableAutoScale: true
    labels:
      test1: test1
      test2: test2
    maxSize: 6
    minSize: 1
    multiZoneSubnetPolicy: EQUALITY
    name: mynodepool
    nodeConfig:
    - extraArgs:
      - root-dir=/var/lib/kubelet
    retryPolicy: INCREMENTAL_INTERVALS
    subnetIds:
    - ${data.tencentcloud_vpc_subnets.vpc.instance_list.0.subnet_id}
    taints:
    - effect: PreferNoSchedule
      key: test_taint
      value: taint_value
    - effect: PreferNoSchedule
      key: test_taint2
      value: taint_value2
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: tencentcloud_vpc_subnets

---

apiVersion: tke.tencentcloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: tke/v1alpha1/nodepool
  labels:
    testing.upbound.io/example-name: managed_cluster
  name: managed-cluster
spec:
  forProvider:
    clusterCidr: ${var.cluster_cidr}
    clusterDeployType: MANAGED_CLUSTER
    clusterDesc: test cluster desc
    clusterMaxPodNum: 32
    clusterMaxServiceNum: 32
    clusterName: tf-tke-unit-test
    clusterVersion: 1.18.4
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: tencentcloud_vpc_subnets
