apiVersion: ssm.tencentcloud.crossplane.io/v1alpha1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: ssm/v1alpha1/secretversion
  labels:
    testing.upbound.io/example-name: v1
  name: v1
spec:
  forProvider:
    secretName: ${tencentcloud_ssm_secret.example.secret_name}
    secretString: this is secret string
    versionId: v1

---

apiVersion: ssm.tencentcloud.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: ssm/v1alpha1/secretversion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: desc.
    isEnabled: true
    recoveryWindowInDays: 0
    secretName: tf-example
    tags:
      createdBy: terraform
