apiVersion: ssm.tencentcloud.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: ssm/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: desc.
    isEnabled: true
    recoveryWindowInDays: 0
    secretName: tf-example
    tags:
      createBy: terraform
