apiVersion: mariadb.tencentcloud.crossplane.io/v1alpha1
kind: DedicatedclusterDBInstance
metadata:
  annotations:
    meta.upbound.io/example-id: mariadb/v1alpha1/dedicatedclusterdbinstance
  labels:
    testing.upbound.io/example-name: dedicatedcluster_db_instance
  name: dedicatedcluster-db-instance
spec:
  forProvider:
    clusterId: dbdc-24odnuhr
    dbVersionId: "8.0"
    goodsNum: 1
    instanceName: cluster-mariadb-test-1
    memory: 2
    storage: 10
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
