apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: GrafanaNotificationChannel
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/grafananotificationchannel
  labels:
    testing.upbound.io/example-name: grafanaNotificationChannel
  name: grafananotificationchannel
spec:
  forProvider:
    channelName: tf-channel
    extraOrgIds:
    - "1"
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    orgId: 1
    receivers:
    - ${tencentcloud_monitor_alarm_notice.foo.amp_consumer_id}

---

apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: AlarmNotice
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/grafananotificationchannel
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: tf_alarm_notice
    noticeLanguage: zh-CN
    noticeType: ALL
    urlNotices:
    - endTime: 0
      startTime: 1
      url: https://www.mytest.com/validate
      weekday:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    userNotices:
    - endTime: 1
      groupIds: []
      needPhoneArriveNotice: 1
      noticeWay:
      - SMS
      - EMAIL
      phoneCallType: CIRCLE
      phoneCircleInterval: 50
      phoneCircleTimes: 2
      phoneInnerInterval: 60
      phoneOrder:
      - 10001
      receiverType: USER
      startTime: 0
      userIds:
      - 10001
      weekday:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7

---

apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: GrafanaInstance
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/grafananotificationchannel
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    enableInternet: false
    grafanaInitPassword: "1234567890"
    instanceName: test-grafana
    subnetIds:
    - ${tencentcloud_subnet.subnet.id}
    tags:
      createdBy: test
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/grafananotificationchannel
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.1.0/24
    name: tf_monitor_subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/grafananotificationchannel
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: tf_monitor_vpc
