apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: PolicyBindingObject
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/policybindingobject
  labels:
    testing.upbound.io/example-name: binding
  name: binding
spec:
  forProvider:
    dimensions:
    - dimensionsJson: '{"unInstanceId":"${data.tencentcloud_instances.instances.instance_list[0].instance_id}"}'
    policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: policy

---

apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: AlarmPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/policybindingobject
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    conditions:
    - isUnionRule: 1
      rules:
      - continuePeriod: 1
        isPowerNotice: 0
        metricName: CpuUsage
        noticeFrequency: 3600
        operator: ge
        period: 60
        value: "89.9"
    enable: 1
    eventConditions:
    - metricName: ping_unreachable
    - metricName: guest_reboot
    monitorType: MT_QCE
    namespace: cvm_device
    noticeIdsRefs:
    - name: example
    policyName: hello
    projectId: 1244035
    triggerTasks:
    - taskConfig: '{"Region":"ap-guangzhou","Group":"asg-0z312312x","Policy":"asp-ganig28"}'
      type: AS
