apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: TmpAlertRule
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmpalertrule
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    annotations:
    - key: description
      value: 'MySQL 连接数过多, 实例: {{$labels.instance}}，当前值: {{ $value | humanizePercentage
        }}。'
    - key: summary
      value: MySQL 连接数过多(>80%)
    duration: 2m
    expr: avg by (instance) (mysql_global_status_threads_connected) / avg by (instance)
      (mysql_global_variables_max_connections)  > 0.8
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    labels:
    - key: severity
      value: warning
    receivers:
    - notice-f2svbu3w
    ruleName: MySQL 连接数过多
    ruleState: 2
    type: MySQL/MySQL 连接数过多

---

apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: TmpCvmAgent
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmpalertrule
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    name: tf-agent

---

apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: TmpInstance
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmpalertrule
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    dataRetentionTime: 30
    instanceName: tf-tmp-instance
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    tags:
      createdBy: terraform
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc
    zone: ${var.availability_zone}

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmpalertrule
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.1.0/24
    name: tf_monitor_subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmpalertrule
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: tf_monitor_vpc
