apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: TmpTkeTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmptketemplate
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    template:
    - describe: template
      level: cluster
      name: tf-template
      podMonitors:
      - config: |
          apiVersion: monitoring.coreos.com/v1
          kind: PodMonitor
          metadata:
            name: example-pod-monitor
            namespace: monitoring
            labels:
              k8s-app: example-pod
          spec:
            selector:
              matchLabels:
                k8s-app: example-pod
            namespaceSelector:
              matchNames:
                - default
            podMetricsEndpoints:
            - port: http-metrics
              interval: 30s
              path: /metrics
              scheme: http
              bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              tlsConfig:
                insecureSkipVerify: true
        name: tf-PodMonitors
      - config: |
          scrape_configs:
            - job_name: 'example-job'
              scrape_interval: 30s
              static_configs:
                - targets: ['example-service.default.svc.cluster.local:8080']
              metrics_path: /metrics
              scheme: http
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                insecure_skip_verify: true
        name: tf-RawJobs
      serviceMonitors:
      - config: |
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: example-service-monitor
            namespace: monitoring
            labels:
              k8s-app: example-service
          spec:
            selector:
              matchLabels:
                k8s-app: example-service
            namespaceSelector:
              matchNames:
                - default
            endpoints:
            - port: http-metrics
              interval: 30s
              path: /metrics
              scheme: http
              bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              tlsConfig:
                insecureSkipVerify: true
        name: tf-ServiceMonitor
