apiVersion: tcr.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: tcr/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    instanceType: basic
    name: tf-example-tcr
    tags:
      createdBy: terraform
