apiVersion: tcr.tencentcloud.crossplane.io/v1alpha1
kind: VpcAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: tcr/v1alpha1/vpcattachment
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: tcr.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: tcr/v1alpha1/vpcattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    deleteBucket: true
    instanceType: basic
    name: tf-example-tcr
    tags:
      createdBy: terraform
