apiVersion: gaap.tencentcloud.crossplane.io/v1alpha1
kind: Layer4Listener
metadata:
  annotations:
    meta.upbound.io/example-id: gaap/v1alpha1/layer4listener
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    healthCheck: true
    name: ci-test-gaap-4-listener
    port: 80
    protocol: TCP
    proxyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    realserverBindSet:
    - id: ${tencentcloud_gaap_realserver.foo.id}
      ip: 1.1.1.1
      port: 80
    - id: ${tencentcloud_gaap_realserver.bar.id}
      ip: 1.1.1.1
      port: 80
    realserverType: IP

---

apiVersion: gaap.tencentcloud.crossplane.io/v1alpha1
kind: Proxy
metadata:
  annotations:
    meta.upbound.io/example-id: gaap/v1alpha1/layer4listener
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    accessRegion: SouthChina
    bandwidth: 10
    concurrent: 2
    name: ci-test-gaap-proxy
    realserverRegion: NorthChina

---

apiVersion: gaap.tencentcloud.crossplane.io/v1alpha1
kind: Realserver
metadata:
  annotations:
    meta.upbound.io/example-id: gaap/v1alpha1/layer4listener
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    ip: 119.29.29.29
    name: ci-test-gaap-realserver2

---

apiVersion: gaap.tencentcloud.crossplane.io/v1alpha1
kind: Realserver
metadata:
  annotations:
    meta.upbound.io/example-id: gaap/v1alpha1/layer4listener
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    ip: 1.1.1.1
    name: ci-test-gaap-realserver
