apiVersion: gaap.tencentcloud.crossplane.io/v1alpha1
kind: Proxy
metadata:
  annotations:
    meta.upbound.io/example-id: gaap/v1alpha1/proxy
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    accessRegion: SouthChina
    bandwidth: 10
    concurrent: 2
    name: ci-test-gaap-proxy
    realserverRegion: NorthChina
    tags:
      test: test
